[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
flare = "${FLARE_RPC_URL}"
coston2 = "${COSTON2_RPC_URL}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
